### ISSUE TITLE
Add links to the Navbar

### ISSUE THREAD

**Issue by sonalsk** [iamHrithikRaj/bug-busters-portfolio#20]
From MLH-Fellowship/pod-3.1.2-portfolio [Issue 7](https://github.com/MLH-Fellowship/pod-3.1.2-portfolio/issues/7#issue-944650392)

Add links to the navbar to navigate to the relevant sections (eg. projects, experience) of the page.
Also, it would be great if we can have an option to choose whether we want to make the navbar sticky or not.

**Comment by iamHrithikRaj** [comment]
@sonalsk i guess we can close this one. right?

**Comment by sonalsk** [comment]
Oh no, we haven't added the navigation links yet. I am waiting for the final navbar to get merged.
