### ISSUE TITLE
Dark mode hides card text

### ISSUE THREAD

**Issue by oorjitchowdhary** [iamHrithikRaj/bug-busters-portfolio#23]
When I toggled to dark mode, the text color changed to white that caused it to appear hidden. I think we can implement a darker bg color for the cards for the dark mode style to fix this.

### Screenshot
![image](https://user-images.githubusercontent.com/39333058/126882169-8c8957f9-a55b-4e59-b7ed-e4dd040d9b60.png)

**Comment by iamHrithikRaj** [comment]
#7 accounts for this bug
