### ISSUE TITLE
Footer not at the bottom

### ISSUE THREAD

**Issue by iamHrithikRaj** [iamHrithikRaj/bug-busters-portfolio#31]
The footer should stick to the bottom.

<img width="1440" alt="Screen Shot 2021-07-25 at 9 20 52 PM" src="https://user-images.githubusercontent.com/50907893/126905250-6936c393-ace2-4d74-bbfd-5e5b210e4bc4.png">

**Comment by sonalsk** [comment]
This is happening because the dark theme toggler is placed after the footer in the landing page. This can be fixed if we move the toggler to the footer or above the footer.
