### ISSUE TITLE
`left-align` banner bio text

### ISSUE THREAD

**Issue by iamHrithikRaj** [iamHrithikRaj/bug-busters-portfolio#34]
Left aligning text in the bio section will make the section look more symmetrical

<img width="1194" alt="Screen Shot 2021-07-25 at 9 27 32 PM" src="https://user-images.githubusercontent.com/50907893/126905493-f4adef5e-813b-49f5-9814-113510643efc.png">

**Comment by sonalsk** [comment]
Fixed this
