### ISSUE TITLE
Cards across the website are not consistent

### ISSUE THREAD

**Issue by iamHrithikRaj** [iamHrithikRaj/bug-busters-portfolio#35]
The cards from education, work exp are different. A common layout for cards can be designed

<img width="1440" alt="Screen Shot 2021-07-25 at 9 30 53 PM" src="https://user-images.githubusercontent.com/50907893/126905576-c97c8298-74b5-47aa-8f36-71897cfd04c0.png">

**Comment by sonalsk** [comment]
I can take this up.
